
management:
  endpoints:
    web:
      exposure:
        include: '*'


dubbo:
  scan:
    base-packages: com.orrin.scali
  protocol:
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
  registry:
    # 挂载到 Spring Cloud 注册中心
    #address: spring-cloud://localhost
    address: nacos://nacos-srv:8848

feign:
  sentinel:
    enabled: true

logging:
  level:
    root: info